# Branch Protection Rules for CatKMP
# This file defines the protection rules for main and develop branches

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        require_last_push_approval: false
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true
      require_signed_commits: false
      require_linear_history: false
      lock_branch: false
      allow_fork_syncing: true
      
  - name: develop
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        require_last_push_approval: false
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true
      require_signed_commits: false
      require_linear_history: false
      lock_branch: false
      allow_fork_syncing: true

# Note: This configuration should be applied through GitHub's web interface
# or using GitHub CLI/API, as this YAML file is for documentation purposes 